package br.com.softnutri.enuns;

public enum PaperAll {
	FOOD_GET, FOOD_POST, FOOD_DELET, FOOD_PUT,
	PATIENT_GET, PATIENT_POST, PATIENT_DELET, PATIENT_PUT,
	PROFESSIONAL_GET, PROFESSIONAL_POST, PROFESSIONAL_DELET, PROFESSIONAL_PUT,
	MENU_GET, MENU_POST, MENU_DELET, MENU_PUT,
	PERMISSION_GET, PERMISSION_POST, PERMISSION_DELET, PERMISSION_PUT,
	CALENDAR_GET, CALENDAR_POST, CALENDAR_DELET, CALENDAR_PUT,
	HOME_GET;
}
