package br.com.softnutri.enuns;

public enum PaperAll {
	
	REGISTER_FOOD_GET, REGISTER_FOOD_POST, REGISTER_FOOD_DELET, REGISTER_FOOD_PUT,
	REGISTER_PATIENT_GET, REGISTER_PATIENT_POST, REGISTER_PATIENT_DELET, REGISTER_PATIENT_PUT,
	REGISTER_PROFESSIONAL_GET, REGISTER_PROFESSIONAL_POST, REGISTER_PROFESSIONAL_DELET, REGISTER_PROFESSIONAL_PUT,
	REGISTER_MENU_GET, REGISTER_MENU_POST, REGISTER_MENU_DELET, REGISTER_MENU_PUT,
	PERMISSION_GET, PERMISSION_POST, PERMISSION_DELET, PERMISSION_PUT,
	CALENDAR_GET, CALENDAR_POST, CALENDAR_DELET, CALENDAR_PUT,
	HOME_PAGE_GET;

}
