package br.com.softnutri.enuns;

public enum PaperAll {
	
	REGISTER_FOOD_GET, REGISTER_FOOD_POST, REGISTER_FOOD_DELET, REGISTER_FOOD_PUT,
	REGISTER_PATIENT_GET, REGISTER_PATIENT_POST, REGISTER_PATIENT_DELET, REGISTER_PATIENT_PUT,
	REGISTER_MENU_GET, REGISTER_MENU_POST, REGISTER_MENU_DELET, REGISTER_MENU_PUT,
	HOME_PAGE_GET;

}
